name: Build Armbian

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started

env:
  UPLOAD_IMAGE: true
  CUSTOMIZATIOM_SCRIPT: userpatches/customize-image.sh
  KERNEL_CONFIG: config

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download source code
      run: |
        pwd
        echo   $GITHUB_WORKSPACE
        git clone --depth=1 --branch=main https://github.com/armbian/build
        # curl -L -o armbian.tar.gz $(curl https://api.github.com/repos/armbian/build/releases | awk -F"[tarball_url]" '/tarball_url/{print $x}' | grep $RELEASE_SOURCE_TAG | sed 's/"//g' | sed 's/tarball_url://g' | sed 's/ //g' | sed 's/,//g')
        # tar -xzf armbian.tar.gz
        # rm -rf armbian.tar.gz

#    - name: Download Armbian Kernel
#      run: |
#        cd build
#        echo "cp kernel config"
#        mkdir $GITHUB_WORKSPACE/build/cache/sources/linux-kernel-worktree/6.1__sunxi__armhf/
#        [ -e $CUSTOMIZATIOM_SCRIPT ] && cp $GITHUB_WORKSPACE/$KERNEL_CONFIG /$GITHUB_WORKSPACE/build/cache/sources/linux-kernel-worktree/6.1__sunxi__armhf/.config
#        echo "./compile.sh kernel-config BOARD=nanopineo BRANCH=current BUILD_MINIMAL=no RELEASE=jammy"
#        ./compile.sh kernel-config BOARD=nanopineo BRANCH=current BUILD_MINIMAL=no RELEASE=jammy
        
    - name: Build Armbian
      id: build
      run: |
        # cd build
        # ./compile.sh build BOARD=nanopineo BRANCH=current BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=jammy
        # echo "cp userpatches/customize-image.sh"
        # [ -e $CUSTOMIZATIOM_SCRIPT ] && mv $GITHUB_WORKSPACE/$CUSTOMIZATIOM_SCRIPT userpatches/customize-image.sh
        # echo "./compile.sh build BOARD=nanopineo BRANCH=current BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=jammy"
        # ./compile.sh build BOARD=nanopineo BRANCH=current BUILD_MINIMAL=no KERNEL_CONFIGURE=no RELEASE=jammy
        echo "::set-output name=status::success"
        #  cd  output/images
        # tar -Jcvf /tmp/nanopi_neo_image.tar.xz  *.img
        tar -Jcvf /tmp/nanopi_neo_image.tar.xz build
        

    - name: Upload Armbian image
      uses: actions/upload-artifact@master
      if: steps.build.outputs.status == 'success'
      with:
        name: Nanopi_neo_image
        path: /tmp/nanopi_neo_image.tar.xz
        
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: steps.build.outputs.status == 'success' && !cancelled()
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          /tmp/nanopi_neo_image.tar.xz 
